# Generated by Django 5.0.1 on 2024-02-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_driver_address_alter_driver_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/driver'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/rider'),
        ),
    ]
